### ISSUE TITLE
Telegram Cards issues on iOS (tried on iPhone 5 and iPhone SE)

### ISSUE THREAD

**Issue by prittandrani** [urbanriskmap/riskmap#225] opened 2017-08-21 04:18 UTC
_ It won’t read your location so it always points you to Monas (Central Jakarta), will be an issue for people esp outside Jakarta to point their location as it also does not have the “Locate Me” button
![whatsapp image 2017-08-21 at 11 17 13](https://user-images.githubusercontent.com/22338984/29503516-7552160a-8662-11e7-952f-718439256da8.jpeg)

_ The “Take Photo” option can’t open the camera -- if this cannot be fixed, our suggestion is to erase the “Take Photo” option and leaving only the “Photo Library” option
![whatsapp image 2017-08-21 at 11 17 13 1](https://user-images.githubusercontent.com/22338984/29503518-78fe9706-8662-11e7-909e-4cdc1195b889.jpeg)

**Comment by talltom** [comment] 2017-08-21 14:22
I suspect the location issue is to do with in-app browser permissions on iOS devices, can anyone else comment?

@ojha-url @abrahamq @asbarve - this photo permissions issue keeps cropping up on iOS. Shall we remove take photo button on these devices, as suggested by @prittandrani?

**Comment by talltom** [comment] 2017-08-22 17:54
@prittandrani 
- did you see a notification saying that your GPS location is not found?

**Comment by talltom** [comment] 2017-08-22 17:58
For the camera issue this is related to https://github.com/urbanriskmap/petabencana.id/issues/157
- Telegram in app browser is broken.

**Comment by prittandrani** [comment] 2017-08-23 04:01
@talltom no, it's just go straight to Monas without any notification as the image shown above, and I always put my location services on.

**Comment by asbarve** [comment] 2017-08-23 04:33
Is it iOS? 

Check if Telegram appears on location services in iOS settings (settings>privacy>location services). 

It dose in my phone for some reason, Also the button to geolocation is missing in iOS telegram browser.

In android both works: button as well as auto centering
 
Best
A

**Comment by asbarve** [comment] 2017-08-23 04:35
I meant - it dose not* appear in my settings

**Comment by matthewberryman** [comment] 2017-08-23 05:12
It doesn't appear in settings and is not something we can control for location (also addressed in https://github.com/urbanriskmap/petabencana.id/issues/157 ) , but we can at least let people know in UI they can upload a photo already taken. We could communicate to app developers about this?

**Comment by emirhartato** [comment] 2017-08-23 11:29
I can confirm in iOS, Telegram app doesn't ask for location permission. This is simply Telegram problem (I assume?) 
![img_0459](https://user-images.githubusercontent.com/1563226/29613385-eb126010-882f-11e7-84c5-0d06cb6716a7.PNG)

Until then, for the temporary solution, I always suggest people for opening the card link in safari (by tapping the safari icon from telegram browser) and allowing the location permission.

![presentation1](https://user-images.githubusercontent.com/1563226/29613575-dfc7881a-8830-11e7-9483-cfdcb78246b4.png)

**Comment by abrahamq** [comment] 2017-08-23 12:08
Looks like the workaround that people are using with these issues is to sniff the user agent and direct the user to go to the native browser instead of the in app one. Hacky but works: https://stackoverflow.com/questions/36402330/how-to-prevent-facebook-in-app-browser-from-opening-my-website-links

**Comment by talltom** [comment] 2017-08-23 14:24
@abrahamq - unfortunately the user agent string is not unique for telegram in-app browser.

**Comment by talltom** [comment] 2017-08-24 19:51
- this bug and discussion should be moved to https://github.com/urbanriskmap/cognicity-cards

**Comment by talltom** [comment] 2018-03-12 18:32
Moved this to the cards repository: https://github.com/urbanriskmap/cognicity-cards/issues/25

**Closed by talltom** 2018-03-12 18:32 UTC
Labels: bug
