### ISSUE TITLE
Report images get stuck on Firefox

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/riskmap#251] opened 2017-10-23 16:45 UTC
Expected behavior:
- clicking on a report, opens the popup reports info with the picture assigned to that report

Observed behavior:
- after opening a report (report "i"), clicking on subsequent reports (report "n) on the map shows the same image from the first report (report "i").

![2017-10-23 07 50 16](https://user-images.githubusercontent.com/944642/31901502-9965172c-b7ef-11e7-8bc1-e65d07c2d2e3.png)

Firefox 56.0 Android 7.0

**Comment by matthewberryman** [comment] 2017-11-03 10:42
Reproduced in Firefox desktop 57.0b13

**Comment by matthewberryman** [comment] 2017-11-03 10:45
Correct behaviour in Google Chrome 63.0.3239.30 (Official Build) beta (64-bit) on same OS.

**Comment by ojha-url** [comment] 2017-11-05 22:12
Bug agnostic to platform / browser.
Does not occur if user clicks each time on a new report.
Occurs if user clicks on a report that has previously been viewed, and server responds with status 304
> there is no need for the server to transfer a representation of the target resource because the request indicates that the client, which made the request conditional, already has a valid representation; the server is therefore redirecting the client to make use of that stored representation as if it were the payload of a 200 OK response

Need to find a way to bypass 304, OR have aurelia fetch cached http requests.

**Comment by matthewberryman** [comment] 2017-11-05 23:33
@ojha-url Using those steps I can reproduce on Chrome (desktop). I could also (eventually) reproduce on Chrome without closing the info panel first, although that happens a lot less often than on Firefox (hence my earlier comment).
I can see 304 hits from the images-dev cloudfront but those are for different URLs (when it does fetch the image) and that's expected behaviour and won't cause the problem. When I can reproduce the bug it's not fetching anything new, which suggests it's something client side (along with turning off cache API server side not fixing the issue). I am guessing that it's something in the way the pop-up is loaded and that adding some js code client side triggered on change of document.location  (because a change of location doesn't trigger a get as it's an aurelia path) to force a refresh of the popup info would do the trick.

**Comment by ojha-url** [comment] 2017-11-06 00:27
Thanks @matthewberryman for testing. I've narrowed it down to the way we are switching between info panels - i.e. report info, area extents and gauge info. Closing the panel hides the element, but the component doesn't get detached (Aurelia specific vocab). On reopening, it's binding behavior glitches and no new image requests are made to the server. This might be rectified if the component was properly detached and reattached instead of jQuery show/hide toggle. This will require a complete overhaul of the panel components code, will try and finish in next few days whenever I find time between meetings in India!

**Comment by matthewberryman** [comment] 2017-11-06 01:15
@ojha-url would adding a callback to the .toggle() work? Just a thought (I'm not up to speed with all things aurelia).

**Comment by ojha-url** [comment] 2017-11-06 22:56
Finally traced bug to aurelia conditional binding. 
* Works alright when there's no if.bind 
* Glitches when conditional binding is used, either on the element or its div wrapper

https://github.com/aurelia/templating/issues/363
* Testing show.bind instead of if.bind

**Comment by ojha-url** [comment] 2017-11-06 23:16
Closed via 62e6611001920f1b2915f457a3f59bbe2d2aee2e

**Closed by ojha-url** 2017-11-06 23:16 UTC
Labels: bug

**Comment by matthewberryman** [comment] 2017-11-06 23:17
@ojha-url just tested Chrome 63.0.3239.30 (Official Build) beta (64-bit) and Firefox 57.0b14 (64-bit) on macOS 10.13.2 Beta 1 following above steps and could not reproduce the bug. Thanks for nailing it :)
